name: "🐛Bug report"
title: "🐛[BUG]"
description: 报告一个bug。
labels: 
  - bug
type: Bug
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > 为避免造成更多的麻烦，请在报告issue前，先检查是否有其他人已经报告过相同的问题。[检查是否存在重复](https://github.com/xystudiocode/pyclickmouse/issues)😊
      
      > [!IMPORTANT]
      > 我们不会在gitee上处理issue，请使用github发布。🙋‍♂️

      > [!TIP]
      > 请一次只报告1个问题。😀
- type: input
  attributes:
    label: 🔡Clickmouse版本
    placeholder: X.X.X 或 X.X.X.X
    description: 反馈三位或四位版本号，可前往"帮助" - "关于"界面查看当前clickmouse版本号
  validations:
    required: true
- type: dropdown
  attributes:
    label: 🎭你是否从官方版本发现bug
    description: ❗clickmouse官方版本只在[github releases](https://github.com/xystudiocode/pyclickmouse/releases)或[gitee releases](https://gitee.com/xystudio889/pyclickmouse/releases)页面发布，其他均为非官方版本。
    multiple: false
    options:
      - ✅是
      - ❌不是
      - ❓我不知道/忘记了
  validations:
    required: true
- id: modules
  type: dropdown
  attributes:
    label: 🐛你运行出现bug的是什么模块？
    description: 🐛你运行出现bug的是什么模块？
    multiple: true
    options:
      - 🖱️连点功能
      - 🧮实时计算和判断连点延迟(包括主窗口，设置和快速连点)
      - ⚙️设置
      - ✳️自适应主题色切换
      - ⌨️热键
      - ️⬜托盘应用
      - ☁️其他主程序功能
      - ⬇️初始化程序
      - 📦包管理器(包括初始化的包管理器)
      - 🗑️卸载程序
      - 🔄️检查更新服务
      - 🔧修复程序
      - ⤴️安装更新
      - 💠其他扩展
      - ♻️清理缓存
      - ❓其他/未知
  validations:
    required: true
- type: textarea
  attributes:
    label: 🐍描述你的bug
    placeholder: |
      请在这描述
    description: 🐍描述你的bug
  validations:
    required: true
- type: input
  attributes:
    label: ℹ️你预估的受影响的Clickmouse版本
    placeholder: |
      >=X.X.X 或 >=X.X.X.X
    description: 🔠反馈大于等于一个三位或四位版本号
  validations:
    required: false
- type: textarea
  attributes:
    label: 📄你的解决步骤想法是什么？
    placeholder: |
      - 解决方案1:
      - 1. 解决步骤1
      - 2. 解决步骤2
      - 3. 解决步骤3
      - 4. 解决步骤...
      - 解决方案2:
      - 1. 解决步骤1
      - 2. 解决步骤2
      - 3. 解决步骤3
      - 4. 解决步骤...
      - 解决方案3:
      - 1. 解决步骤1
      - 2. 解决步骤2
      - 3. 解决步骤3
      - 4. 解决步骤...
      - 其他解决方案...
    description: ♻️可以提供多个Bug解决方案，但请确保每个方案都能解决你的问题。
  validations:
    required: false
- type: textarea
  attributes:
    label: ➕其他相关信息
    placeholder: |
      你使用的操作系统版本、系统语言、造成bug软件等。
    description: ✉️提供更多信息，如操作系统版本、系统语言、造成bug软件等。
  validations:
    required: false