name: Feature
description: 一个你建议添加的新功能。
title: "❇️[FEATURE]"
labels: enhancement
type: Feature
body:
- type: markdown
  attributes:
    value: |
      > [!NOTE]
      > **为避免造成更多的麻烦，请在报告issue前，先检查是否有其他人已经报告过相同的问题。[检查是否存在重复](https://github.com/xystudiocode/pyclickmouse/issues)**😊
      
      > [!IMPORTANT]
      > 我们不会在gitee上处理issue，请使用github发布。🙋‍♂️

      > [!TIP]
      > 请一次只报告1个问题。😀
- id: modules
  type: dropdown
  attributes:
    label: ❇️你想新增功能的是什么模块？
    description: ❇️你想新增功能的是什么模块？
    multiple: true
    options:
      - 🖱️连点功能
      - 🧮实时计算和判断连点延迟(包括主窗口，设置和快速连点)
      - ⚙️设置
      - ✳️自适应主题色切换
      - ⌨️热键
      - ️⬜托盘应用
      - ☁️其他主程序功能
      - ⬇️初始化程序
      - 📦包管理器(包括初始化的包管理器)
      - 🗑️卸载程序
      - 🔄️检查更新服务
      - 🔧扩展修复程序
      - ⤴️安装更新
      - 💠其他扩展
      - ❓其他/未知
  validations:
    required: true
- id: feature_description
  type: textarea
  attributes:
    label: 📄请详细描述你想要新增的功能。
    placeholder: |
      详细描述你想要新增的功能
    value: |
      新功能
    description: 📄请详细描述你想要新增的功能。
  validations:
    required: true
- id: feature_reason
  type: textarea
  attributes:
    label: ❔为什么需要这个功能？
    placeholder: |
      解决了什么问题？
      增加了什么功能？
      改进了什么？
      其他原因...
    value: |
      解决了什么问题？
      增加了什么功能？
      改进了什么？
      其他原因...
    description: ❔为什么需要这个功能？
  validations:
    required: false
- id: resolution_solution
  type: textarea
  attributes:
    label: 🧾你的实行步骤想法是什么？
    placeholder: |
      - 实行方案1:
      - 1. 实行步骤1
      - 2. 实行步骤2
      - 3. 实行步骤3
      - 4. 实行步骤...
      - 实行方案2:
      - 1. 实行步骤1
      - 2. 实行步骤2
      - 3. 实行步骤3
      - 4. 实行步骤...
      - 实行方案3:
      - 1. 实行步骤1
      - 2. 实行步骤2
      - 3. 实行步骤3
      - 4. 实行步骤...
      - 其他实行方案...
    value: |
      - 实行方案1:
      - 1. 实行步骤1
      - 2. 实行步骤2
      - 3. 实行步骤3
      - 4. 实行步骤...
      - 实行方案2:
      - 1. 实行步骤1
      - 2. 实行步骤2
      - 3. 实行步骤3
      - 4. 实行步骤...
      - 实行方案3:
      - 1. 实行步骤1
      - 2. 实行步骤2
      - 3. 实行步骤3
      - 4. 实行步骤...
      - 其他实行方案...
    description: ♻️可以提供多个新功能实行方案，但请确保每个方案都能实行你的需求。
  validations:
    required: false
- id: Additional
  type: textarea
  attributes:
    label: ➕其他相关信息
    description: 📄你了解到的更多内容
    placeholder: |
      更多信息。
  validations:
    required: false